name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch: # for manual workflow trigger
  schedule:
    # Runs every two minute
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: "waka-readme"
          COMMIT_MESSAGE: "waka update time stats"
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
